/// Flutter icons PriorityCustomIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PriorityCustomIcons
///      fonts:
///       - asset: fonts/PriorityCustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class PriorityCustomIcons {
  PriorityCustomIcons._();

  static const _kFontFam = 'PriorityCustomIcons';
  static const String? _kFontPkg = null;

  static const IconData medium = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData low = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData high = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData asap = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
